const { AUTH_ACCESS_TIMEOUT } = require('./AUTH_ACCESS_TIMEOUT')
const { AUTH_FAILED } = require('./AUTH_FAILED')
const { AUTH_REFRESH_TIMEOUT } = require('./AUTH_REFRESH_TIMEOUT')
const { AUTH_UNAUTHORIZED } = require('./AUTH_UNAUTHORIZED')
const { RANGE_ERROR } = require('./RANGE_ERROR')
const { UNCAUGHT_ERROR } = require('./UNCAUGHT_ERROR')

module.exports = {
  AUTH_ACCESS_TIMEOUT,
  AUTH_FAILED,
  AUTH_REFRESH_TIMEOUT,
  AUTH_UNAUTHORIZED,
  RANGE_ERROR,
  UNCAUGHT_ERROR
}
